name: vaccineSimulator
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.10
  - pip
  - jupyterlab=3.4.7
  - matplotlib=3.8.0
  - numba=0.57.1
  - numpy=1.24.4
  - scipy=1.11.3
  - leidenalg=0.10.1
  - scikit-learn=1.1.3
  - tqdm=4.66.1
  - umap-learn=0.5.4
  - pip:
    - seaborn==0.11.2
    - pandas==1.5.3
    - anndata==0.10.1
    - scanpy==1.9.5
    - mudata==0.2.3
    - muon==0.1.5
    - scirpy==0.13.1
    - decoupler==1.5.0
    - liana==1.3.0